language: node_js

node_js: "8"

cache: npm

before_deploy: npm run build -- -prod

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  verbose: true
  on:
    branch: master

